function Hd = bandpass
%BANDPASS 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 24.1 and Signal Processing Toolbox 24.1.
% Generated on: 22-May-2025 19:59:08

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 200000000;  % Sampling Frequency

N      = 100;       % Order
Fstop1 = 21000000;  % First Stopband Frequency
Fpass1 = 25000000;  % First Passband Frequency
Fpass2 = 75000000;  % Second Passband Frequency
Fstop2 = 79000000;  % Second Stopband Frequency
Wstop1 = 1;         % First Stopband Weight
Wpass  = 1;         % Passband Weight
Wstop2 = 1;         % Second Stopband Weight
dens   = 20;        % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fstop1 Fpass1 Fpass2 Fstop2 Fs/2]/(Fs/2), [0 0 1 1 0 ...
           0], [Wstop1 Wpass Wstop2], {dens});
Hd = dfilt.dffir(b);

% [EOF]
